sudo: false

language: node_js

node_js:
  - 10
  - 8

script: yarn test

cache:
  yarn: true
  directories:
    - node_modules

branches:
  except:
    - /^v[0-9]/

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
