sudo: false

language: node_js

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2

node_js:
  - 8 
  - 6
  - 4

cache:
  yarn: true
  directories:
    - node_modules

branches:
  except:
    - /^v[0-9]/

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
