sudo: false

language: node_js

node_js:
  - 8 
  - 6
  - 4

cache:
  directories:
    - node_modules

cache: yarn

branches:
  except:
    - /^v[0-9]/

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
